[package]
name = "reswmm-core"
version = "0.1.0"
authors = ["Reese Walton <jrwalt4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.uom]
version = "0.29"
default-features = false
features = [
    "i32", "i64", "f32", "f64", 
    "si", "std"
]
