[package]
name = "reswmm-core"
version = "0.1.0"
authors = ["Reese Walton <jrwalt4@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
furlong = { path = "../furlong"}
enum_dispatch = "0.3"

[features]
custom_nodes = []
custom_links = []
custom_elements = ["custom_nodes", "custom_links"]
